server:
  port: 8080
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com.example.mapper: debug

# spring配置
spring:
  profiles:
    active: "dev"
  datasource:
    password: Zql@20040712
    username: root
    url: jdbc:mysql://localhost:3306/blog?characterEncoding=utf-8&serverTimezone=GMT%2B8
  data:
    redis:
      host: localhost      # 本地开发填 localhost；云服务填控制台给的地址
      port: 6379           # Redis 默认端口
      password: ""         # 本地无密码可空；云服务（如 Azure Redis）必填！
      database: 0          # Redis 有 16 个库（0～15），开发常用 0
      timeout: 2000ms      # 操作超时时间
  mail:
    username: 3100649706@qq.com
  security:
    jwt:
      key: jwt-key
      expire: 7 # 有效时间
  rabbitmq:
    # rabbitmq配置
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true # 允许消费者重试
          max-attempts: 3 # 最大重试次数
          initial-interval: 6000 # 重试间隔时间
          multiplier: 2 # 乘子*间隔时间=下一次重试时间，不能超过最大间隔时间
          max-interval: 10000ms # 最大间隔时间
    # 信息配置
    # 交换机，相当于分拣中心
    exchange:
      email: email_exchange
      log: log_exchange
    # 队列，相当于仓库货架
    queue:
      email: email_queue
      log-login: log_login_queue
      log-system: log_system_queue
    # 路由健，相当于货架上的标签
    routingKey:
      log-login: log_routing_key_login
      log-system: log_routing_key_system
      email: email_routing_key

# 邮件配置
mail:
  article-email-notice: false
  message-email-notice: false
  article-reply-notice: false
  message-reply-notice: false

# 对象存储配置
minio:
  bucketName: bn
  endpoint: http://localhost:9000
  accessKey: minioadmin
  secretKey: minioadmin
