INSERT INTO `t_category` VALUES (1, '生活', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO `t_category` VALUES (2, '技术', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO `t_category` VALUES (3, '娱乐', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO `t_category` VALUES (4, '分类', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO `t_category` VALUES (5, '测试', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `t_category` VALUES (9, '测添加', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `t_category` VALUES (10, '修改', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);