INSERT INTO `t_like` VALUES (257, 1, 2, 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `t_like` VALUES (261, 1, 3, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `t_like` VALUES (262, 1, 3, 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `t_like` VALUES (263, 1, 2, 46, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `t_like` VALUES (264, 1, 2, 41, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `t_like` VALUES (269, 1, 2, 26, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `t_like` VALUES (283, 1, 1, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);