INSERT INTO `t_tag` VALUES (1, 'java', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO `t_tag` VALUES (2, 'python', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO `t_tag` VALUES (3, 'c#', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO `t_tag` VALUES (4, 'c++', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO `t_tag` VALUES (5, '开心', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);