INSERT INTO `t_tree_hole` VALUES (1, 1, '测试添加', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO `t_tree_hole` VALUES (29, 1, '真的是服了！！', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO `t_tree_hole` VALUES (30, 1, '记得一定要快乐啊！！', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO `t_tree_hole` VALUES (34, 1, '天天开心', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
