/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BackgroundImage: typeof import('./../components/BackgroundImage.vue')['default']
    BottomRightLayout: typeof import('./../components/BottomRightLayout/index.vue')['default']
    BottomRightMore: typeof import('./../components/BottomRightMore.vue')['default']
    Card: typeof import('./../components/Card.vue')['default']
    ContextMenu: typeof import('./../components/ContextMenu/index.vue')['default']
    DevToolsBlocker: typeof import('./../components/DevToolsBlocker/index.vue')['default']
    ElectronicClocks: typeof import('./../components/ElectronicClocks.vue')['default']
    EssayCard: typeof import('./../components/EssayCard.vue')['default']
    Footer: typeof import('./../components/Layout/Footer/index.vue')['default']
    FullScreen: typeof import('./../components/FullScreen.vue')['default']
    GlitchText: typeof import('./../components/GlitchText.vue')['default']
    Header: typeof import('./../components/Layout/Header/index.vue')['default']
    InfoCard: typeof import('./../components/InfoCard.vue')['default']
    Loading: typeof import('./../components/Loading/index.vue')['default']
    Menu: typeof import('./../components/Layout/Header/Menu/index.vue')['default']
    MouseTrail: typeof import('./../components/MouseTrail.vue')['default']
    MoveMenu: typeof import('./../components/Layout/Header/MoveMenu/index.vue')['default']
    Music: typeof import('./../components/Music/index.vue')['default']
    Pagination: typeof import('./../components/Pagination.vue')['default']
    Particles: typeof import('./../components/Particles.vue')['default']
    RandomArticle: typeof import('./../components/RandomArticle.vue')['default']
    ReadingMode: typeof import('./../components/ReadingMode.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollParallel: typeof import('./../components/ScrollParallel/index.vue')['default']
    Search: typeof import('./../components/Search/index.vue')['default']
    SideBar: typeof import('./../components/SideBar.vue')['default']
    SvgIcon: typeof import('./../components/SvgIcon/index.vue')['default']
    ToComment: typeof import('./../components/ToComment.vue')['default']
    ToTop: typeof import('./../components/ToTop.vue')['default']
    Wave: typeof import('./../components/Wave.vue')['default']
  }
}
