/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ContextMenu: typeof import('./../components/ContextMenu/index.vue')['default']
    DevToolsBlocker: typeof import('./../components/DevToolsBlocker/index.vue')['default']
    Header: typeof import('./../components/Layout/Header/index.vue')['default']
    HelloWorld: typeof import('./../components/HelloWorld.vue')['default']
    Loading: typeof import('./../components/Loading/index.vue')['default']
    Music: typeof import('./../components/Music/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
